"""Export Python contracts and their deliberately limited DSH schema projection.

Run from an editable backend install: python -m aifs.contracts --write / --check.
JSON Schema retains backend constraints; DSH supports shape, types and enums,
but numeric/length/conditional scientific checks still run in Python.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

from aifs.evidence_models import EvidenceSearchRequest, EvidenceSearchResponse
from aifs.models import (
    RestInputRequest,
    RestInputResponse,
    ValidateInputRequest,
    ValidateInputResponse,
)
from aifs.rest.catalogs import ALLOWED_OUTPUTS
from aifs.workflow_models import PlanDraft, PlanRevisionRequest

CONTRACT_VERSION = 1
MODELS = {
    "PLAN_DRAFT_SCHEMA": PlanDraft,
    "PLAN_REVISION_SCHEMA": PlanRevisionRequest,
    "REST_INPUT_SCHEMA": RestInputRequest,
    "VALIDATE_INPUT_SCHEMA": ValidateInputRequest,
    "REST_RESPONSE_SCHEMA": RestInputResponse,
    "VALIDATE_RESPONSE_SCHEMA": ValidateInputResponse,
    "EVIDENCE_REQUEST_SCHEMA": EvidenceSearchRequest,
    "EVIDENCE_RESPONSE_SCHEMA": EvidenceSearchResponse,
}


def project_schema(schema: dict[str, Any], defs: dict[str, Any] | None = None) -> dict:
    """Resolve references and project only the schema features DSH can enforce."""
    defs = schema.get("$defs", {}) if defs is None else defs
    if "$ref" in schema:
        ref = schema["$ref"]
        if not ref.startswith("#/$defs/"):
            raise ValueError(f"Unsupported schema reference: {ref}")
        return project_schema(defs[ref.removeprefix("#/$defs/")], defs)
    if "anyOf" in schema:
        branches = [project_schema(branch, defs) for branch in schema["anyOf"]]
        # Pydantic's nullable unions are disjoint. Overlapping anyOf cannot
        # become DSH's exact-one union without changing its meaning.
        if len(branches) != 2 or not any(branch == {"type": "null"} for branch in branches):
            raise ValueError("Unsupported overlapping union; add an explicit projection")
        return {"oneOf": branches}
    kind = schema.get("type")
    if kind is None:
        if set(schema) - {"title", "description", "default"}:
            raise ValueError(f"Unsupported schema node: {schema}")
        return {"type": "json"}
    result: dict[str, Any] = {"type": kind}
    for key in ("enum", "const"):
        if key in schema:
            result[key] = schema[key]
    if kind == "object":
        result["additionalProperties"] = schema.get("additionalProperties", False) is not False
        if "properties" in schema:
            required = schema.get("required", [])
            result["properties"] = {
                name: {
                    **project_schema(child, defs),
                    **({"required": True} if name in required else {}),
                }
                for name, child in schema["properties"].items()
            }
    elif kind == "array":
        result["items"] = project_schema(schema.get("items", {}), defs)
    elif kind not in {"string", "number", "integer", "boolean", "null"}:
        raise ValueError(f"Unsupported schema type: {kind}")
    return result


def contract_artifacts() -> dict[str, str]:
    models = {model.__name__: model.model_json_schema() for model in MODELS.values()}
    # This enum is checked by a Python validator rather than a Literal field.
    models["RestInputRequest"]["properties"]["outputs"]["items"]["enum"] = sorted(ALLOWED_OUTPUTS)
    source = (
        "// Generated by python -m aifs.contracts --write. Do not edit.\n"
        "// Shape/types/enums only; full constraints remain in Python and backend-schema.json.\n"
        "import type { ValueSchemaSpec } from '@deepseek-ai/dsh-tools'\n\n"
        f"export const CONTRACT_VERSION = {CONTRACT_VERSION}\n\n"
    )
    for name, model in MODELS.items():
        projected = project_schema(models[model.__name__])
        source += (
            f"export const {name} = "
            + json.dumps(projected, ensure_ascii=False, indent=2)
            + " as const satisfies ValueSchemaSpec\n\n"
        )
    root = Path(__file__).resolve().parents[3]
    sources = (
        "backend/src/aifs/contracts.py",
        "backend/src/aifs/models.py",
        "backend/src/aifs/workflow_models.py",
        "backend/src/aifs/evidence_models.py",
        "backend/src/aifs/rest/catalogs.py",
    )
    data = {
        "contract_version": CONTRACT_VERSION,
        "source_hashes": {
            path: hashlib.sha256((root / path).read_text(encoding="utf-8").encode()).hexdigest()
            for path in sources
        },
        "generated_ts_sha256": hashlib.sha256(source.encode()).hexdigest(),
        "models": models,
    }
    raw = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    return {
        "contracts/backend-schema.json": raw,
        "dsh-plugin-aifs/src/generated/backend.ts": source,
    }


def synchronize(root: Path, *, check: bool) -> None:
    for relative, expected in contract_artifacts().items():
        path = root / relative
        if check:
            # Normalized checkout line endings do not hide actual contract drift.
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                raise ValueError(f"Contract out of date: {relative}; run aifs.contracts --write")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument("--write", action="store_true")
    modes.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[3])
    args = parser.parse_args()
    synchronize(args.root, check=args.check)
    print("AIFS backend contracts checked" if args.check else "AIFS backend contracts generated")


if __name__ == "__main__":
    main()
