/** __init__.py is the release version source; generated consumers are checked before builds. */
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { join, resolve } from 'node:path'

const defaultRoot = fileURLToPath(new URL('../', import.meta.url))
const readJson = async path => JSON.parse(await readFile(path, 'utf8'))
const writeJson = (path, data) => writeFile(path, JSON.stringify(data, null, 2) + '\n')
const versionSource = version => `// Generated by scripts/release.mjs --sync; edit backend/src/aifs/__init__.py.\nexport const SERVICE_VERSION = '${version}'\n`

export async function releaseVersion(root = defaultRoot) {
  const source = await readFile(join(root, 'backend/src/aifs/__init__.py'), 'utf8')
  const version = /^__version__ = ["']([^"']+)["']$/m.exec(source)?.[1]
  if (!version || !/^\d+\.\d+\.\d+(?:-[\da-zA-Z.-]+)?$/.test(version)) throw new Error('Invalid AIFS release version')
  return version
}

export async function synchronizeRelease(root = defaultRoot) {
  const version = await releaseVersion(root)
  const directory = join(root, 'dsh-plugin-aifs')
  const manifest = await readJson(join(directory, 'package.json'))
  const lock = await readJson(join(directory, 'package-lock.json'))
  manifest.version = lock.version = lock.packages[''].version = version
  await writeJson(join(directory, 'package.json'), manifest)
  await writeJson(join(directory, 'package-lock.json'), lock)
  await writeFile(join(directory, 'src/version.ts'), versionSource(version))
}

export async function checkRelease(root = defaultRoot, { installed = false } = {}) {
  const version = await releaseVersion(root)
  const directory = join(root, 'dsh-plugin-aifs')
  const manifest = await readJson(join(directory, 'package.json'))
  const lock = await readJson(join(directory, 'package-lock.json'))
  if ([manifest.version, lock.version, lock.packages['']?.version].some(value => value !== version)) {
    throw new Error('AIFS version mismatch: run node scripts/release.mjs --sync')
  }
  const runtimeVersion = (await readFile(join(directory, 'src/version.ts'), 'utf8')).replace(/\r\n/g, '\n')
  if (runtimeVersion !== versionSource(version)) {
    throw new Error('Runtime version mismatch: run node scripts/release.mjs --sync')
  }
  const require = createRequire(join(directory, 'package.json'))
  for (const [name, expected] of Object.entries(manifest.devDependencies)) {
    if (!/^\d+\.\d+\.\d+(?:-[\da-zA-Z.-]+)?$/.test(expected)
      || lock.packages[''].devDependencies?.[name] !== expected
      || lock.packages[`node_modules/${name}`]?.version !== expected) {
      throw new Error(`Build dependency lock mismatch: ${name}; update package-lock.json`)
    }
    if (installed && (await readJson(require.resolve(`${name}/package.json`))).version !== expected) {
      throw new Error(`Installed build dependency mismatch: ${name}; run npm ci in dsh-plugin-aifs`)
    }
  }
  if (Object.keys(lock.packages[''].devDependencies || {}).length !== Object.keys(manifest.devDependencies).length) {
    throw new Error('Build dependency lock contains stale entries; update package-lock.json')
  }
  return version
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  if (process.argv.includes('--sync')) await synchronizeRelease()
  console.log(`AIFS ${await checkRelease(defaultRoot, { installed: process.argv.includes('--installed') })}: release metadata checked`)
}
